<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <title>Personas View</title>
</head>
<body>
    <div class="row justify-content-center">
        <form action="" method="POST" name="register">
            <div class="form-group">
                <label>Name</label>
                <input type="text" name="name" class="form-control" placeholder="Introduce nombre...">
            </div>
            <div class="form-group">
                <label>Location</label>
                <input type="text" name="location" class="form-control" placeholder="Introduce ubicacion...">
            </div>
            <div class="form-group">
                <input type="submit" name="save" class="btn btn-primary" value="Save">    
            </div> 
        </form>
    </div>
    <?php
        foreach ($datos as $dato) {
            echo ($dato);
        }
    ?>
</body>
</html>